flush ruleset

table inet filter {
        set banned {
                type ipv4_addr
                flags timeout
        }

        set banned6 {
                type ipv6_addr
                flags timeout
        }

        set banned_net {
                type ipv4_addr
                flags interval,timeout
        }

        set banned_net6 {
                type ipv6_addr
                flags interval,timeout
        }

        chain input {
                type filter hook input priority 0; policy accept;

                # 1. Оптимизация и локальный трафик
                iifname "lo" accept
                ct state established,related accept
                ct state invalid drop

                # 2. Проверка по блэк-листам
                ip6 saddr @banned_net6 drop
                ip saddr @banned_net drop
                ip6 saddr @banned6 drop
                ip saddr @banned drop
        }
}

